### ISSUE TITLE
[Feature]: Add AutoGen from Policy to XML

### ISSUE THREAD

**Issue by os-d** [microsoft/mu_feature_config#356]
### Feature Overview

Many end consumers of config knobs use policy from PolicyServicePkg to get their configuration options. To enable a platform to easily create config knobs that map 1:1 with the policy, create a tool that will generate XML from a given policy structure. This will be intended to help during tuning time and that a platform will craft their configuration options to be meaningful to their platform after this point.

### Solution Overview

See above.

### Urgency

Medium

### Are you going to implement the feature request?

I will implement the feature

### Do you need maintainer feedback?

No maintainer feedback needed

**Comment by MarcChen46** [comment]
Since the XML has multiple fields like name, type, default, help, and the config knob may use a customized type that need to declare Enum, in that case, we may need to define a rule how to put those information in policy structure with comment well, then the tool could generate all the required elements in XML files accordingly.
